"""
Unified CVE Relevance Scorer — SecBERT only
============================================

Dùng SecBERT để tính semantic similarity giữa behavior profile của file PE
và mô tả CVE. Đây là cách duy nhất tính relevance — không còn rule-based
scoring với hardcoded weights nữa.

Khi SecBERT không available:
  → Không fake score, chỉ sort CVEs theo CVSS score (cao nhất trước).

Usage:
    from ai.relevance_scorer import score_cves, is_semantic_available

    cves = score_cves(software_analysis, cves)
    # Each CVE now has: cve['relevance'] = {score, label, method, model}
"""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))

try:
    from secbert_cve_scorer import (
        score_cves_semantic as _sec_score,
        build_profile_text  as _build_profile_text,
        is_available        as _sec_ok,
    )
    _SECBERT_IMPORTED = True
except Exception:
    _SECBERT_IMPORTED = False
    _sec_ok = lambda: False


def score_cves(software_analysis: dict, cves: list) -> list:
    """
    Score CVE relevance using SecBERT semantic similarity.

    Mỗi CVE sẽ có thêm field:
        cve['relevance'] = {
            'score':  float,   # cosine similarity 0.0–1.0 (SecBERT)
            'label':  str,     # CRITICAL / HIGH / MEDIUM / LOW / MINIMAL
            'method': str,     # 'secbert' | 'cvss_only'
            'model':  str,     # tên model đang dùng
        }

    Nếu SecBERT không available:
        → method = 'cvss_only', score = normalized CVSS (0–1), sort by CVSS DESC
    """
    if not cves:
        return cves

    # ── SecBERT semantic scoring ───────────────────────────────────────────────
    if _SECBERT_IMPORTED and _sec_ok():
        try:
            cves = _sec_score(software_analysis, cves)

            # Map secbert_relevance → unified relevance field
            for cve in cves:
                sec = cve.get('secbert_relevance', {})
                cve['relevance'] = {
                    'score':  sec.get('score', 0.0),
                    'label':  sec.get('label', 'MINIMAL'),
                    'method': 'secbert',
                    'model':  sec.get('model', ''),
                }

            # Sort: SecBERT score DESC, then CVSS DESC
            cves.sort(
                key=lambda c: (
                    c.get('relevance', {}).get('score', 0.0),
                    c.get('cvss_score', 0.0),
                ),
                reverse=True,
            )
            return cves

        except Exception:
            pass  # fall through to CVSS-only

    # ── Fallback: sort by CVSS, no fake scoring ────────────────────────────────
    cves.sort(key=lambda c: float(c.get('cvss_score') or 0), reverse=True)
    for cve in cves:
        cvss = float(cve.get('cvss_score') or 0)
        cve['relevance'] = {
            'score':  round(cvss / 10.0, 4),   # normalize 0–10 → 0–1
            'label':  _cvss_label(cvss),
            'method': 'cvss_only',
            'model':  '',
        }
    return cves


def _cvss_label(cvss: float) -> str:
    if cvss >= 9.0:
        return 'CRITICAL'
    if cvss >= 7.0:
        return 'HIGH'
    if cvss >= 4.0:
        return 'MEDIUM'
    if cvss > 0:
        return 'LOW'
    return 'NONE'


def get_profile_text(software_analysis: dict) -> str:
    """Return natural-language behavior profile generated by SecBERT scorer."""
    if _SECBERT_IMPORTED:
        try:
            return _build_profile_text(software_analysis)
        except Exception:
            pass
    return ''


def is_semantic_available() -> bool:
    return _SECBERT_IMPORTED and _sec_ok()
